### ISSUE TITLE
How can I turn off the Inlay Hints

### ISSUE THREAD

**Issue by 22TINEZ51** [GeniusPenguin9/Brainfuck_All_In_One#7]
I've just recently installed the extension and I don't like the inlay hints, is there anyway to turn that off

**Comment by GeniusPenguin9** [comment]
Hi 22TINEZ51,

Add new configuration to enable / disable inlay hints in latest version. Pls update extension to v1.0.3 and play with it. Pay attention, need restart vsc after setting changed.

Feel free to let me know if any question.
